# Generated by Django 3.2.4 on 2021-07-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='ip',
            field=models.CharField(default='', max_length=100),
        ),
    ]
